import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import {
  applyAdjustColor,
  applyAdjustLight,
  applyBlackAndWhite,
  applyUnsharpMask,
  computeMeanRGB,
  gaussianKernel1D,
  rgbToLab,
  type RGBA,
} from './color-math'
import { computeFitGeometry, type FitGeometry } from './geometry'

// Measures V-2 (docs/90-deferred-register.md): drift between color-math.ts's
// pure-TS reference math -- the source both webgpu-renderer.ts and
// webgl2-renderer.ts are hand-transcribed from -- and the real govips
// output the four composite processors produce
// (workers/internal/processors/{adjust_light,adjust_color,black_and_white,sharpen}.go).
// Fixtures are generated by workers/cmd/gendriftfixture and
// workers/cmd/gendriftgolden (docs/tasks/TASK-recipe-fidelity-drift.md) and
// committed to testdata/drift/ -- raw RGBA8 dumps, not PNGs, so this test
// compares the exact pixels govips decoded/produced without a second image
// decoder in the loop.

const FIXTURES_DIR = join(dirname(fileURLToPath(import.meta.url)), '../../../../../testdata/drift')

interface Raster {
  width: number
  height: number
  pixels: RGBA[] // row-major, normalized 0..1
}

function readRaster(path: string): Raster {
  const buf = readFileSync(path)
  const width = buf.readUInt32LE(0)
  const height = buf.readUInt32LE(4)
  const pixels: RGBA[] = new Array(width * height)
  for (let i = 0; i < width * height; i++) {
    const off = 8 + i * 4
    pixels[i] = {
      r: buf[off] / 255,
      g: buf[off + 1] / 255,
      b: buf[off + 2] / 255,
      a: buf[off + 3] / 255,
    }
  }
  return { width, height, pixels }
}

const source = readRaster(join(FIXTURES_DIR, 'source.rgba'))

// Whole-source-image per-band mean, computed once -- image.adjustColor's
// castStrength points below test the control in isolation directly against
// source.pixels, so the mean over the untouched source raster is the
// correct reference (matches what adjust_color.go's applyCast computes
// when image.adjustColor is the first/only step touching the image).
const sourceMeanRGB = computeMeanRGB(source.pixels)

interface DriftResult {
  maeR: number
  maeG: number
  maeB: number
  maxR: number
  maxG: number
  maxB: number
  meanDeltaE: number
}

function measureDrift(actual: RGBA[], golden: RGBA[]): DriftResult {
  let sumR = 0
  let sumG = 0
  let sumB = 0
  let maxR = 0
  let maxG = 0
  let maxB = 0
  let sumDeltaE = 0
  const n = actual.length

  for (let i = 0; i < n; i++) {
    const a = actual[i]
    const g = golden[i]
    const dr = Math.abs(a.r - g.r) * 255
    const dg = Math.abs(a.g - g.g) * 255
    const db = Math.abs(a.b - g.b) * 255
    sumR += dr
    sumG += dg
    sumB += db
    if (dr > maxR) maxR = dr
    if (dg > maxG) maxG = dg
    if (db > maxB) maxB = db

    const labA = rgbToLab(a.r, a.g, a.b)
    const labG = rgbToLab(g.r, g.g, g.b)
    sumDeltaE += Math.hypot(labA.l - labG.l, labA.a - labG.a, labA.b - labG.b)
  }

  return {
    maeR: sumR / n,
    maeG: sumG / n,
    maeB: sumB / n,
    maxR,
    maxG,
    maxB,
    meanDeltaE: sumDeltaE / n,
  }
}

// Separable Gaussian blur, sigma/radius matching workers/internal/processors/sharpen.go's
// fixed img.Sharpen(0.5, 2, ...) call -- mirrors what webgpu-renderer.ts /
// webgl2-renderer.ts run as their blur pass before applyUnsharpMask.
// color-math.ts deliberately only exports the per-pixel unsharp half (the
// blur is a spatial pass belonging to the renderers), so this convolution
// is test-local, not reusable renderer code.
function gaussianBlur(raster: Raster, sigma: number, radius: number): RGBA[] {
  const kernel = gaussianKernel1D(sigma, radius)
  const { width, height, pixels } = raster

  const horizontal: RGBA[] = new Array(width * height)
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      let r = 0
      let g = 0
      let b = 0
      for (let k = -radius; k <= radius; k++) {
        const sx = Math.min(width - 1, Math.max(0, x + k))
        const p = pixels[y * width + sx]
        const w = kernel[k + radius]
        r += p.r * w
        g += p.g * w
        b += p.b * w
      }
      horizontal[y * width + x] = { r, g, b, a: pixels[y * width + x].a }
    }
  }

  const vertical: RGBA[] = new Array(width * height)
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      let r = 0
      let g = 0
      let b = 0
      for (let k = -radius; k <= radius; k++) {
        const sy = Math.min(height - 1, Math.max(0, y + k))
        const p = horizontal[sy * width + x]
        const w = kernel[k + radius]
        r += p.r * w
        g += p.g * w
        b += p.b * w
      }
      vertical[y * width + x] = { r, g, b, a: pixels[y * width + x].a }
    }
  }

  return vertical
}

// Reproduces the *final blit* pass both renderers run for image.resize --
// BLIT_VERTEX_SHADER_SOURCE/BLIT_FRAGMENT_SHADER_SOURCE in
// webgl2-renderer.ts (and the WebGPU equivalent): each output pixel's local
// UV (x+0.5)/outW, (y+0.5)/outH is mixed into computeFitGeometry()'s
// sourceUV rect, then bilinear-sampled from the source texture with
// clamp-to-edge addressing (gl.CLAMP_TO_EDGE, explicit in
// webgl2-renderer.ts; WebGPU's createSampler sets no addressMode, resting
// on the spec default of "clamp-to-edge" -- V-6 flags this as still
// unverified against the spec text directly). Test-local like gaussianBlur
// above -- neither renderer exposes "resample once, return pixels" as a
// unit, they render straight to a canvas.
function bilinearResample(source: Raster, geometry: FitGeometry): Raster {
  const outWidth = Math.max(1, Math.round(geometry.outputWidth))
  const outHeight = Math.max(1, Math.round(geometry.outputHeight))
  const { u0, v0, u1, v1 } = geometry.sourceUV
  const pixels: RGBA[] = new Array(outWidth * outHeight)

  for (let y = 0; y < outHeight; y++) {
    for (let x = 0; x < outWidth; x++) {
      const localU = (x + 0.5) / outWidth
      const localV = (y + 0.5) / outHeight
      const u = u0 + (u1 - u0) * localU
      const v = v0 + (v1 - v0) * localV
      pixels[y * outWidth + x] = sampleBilinearClamped(source, u, v)
    }
  }

  return { width: outWidth, height: outHeight, pixels }
}

// Half-texel-centered UV -> texel mapping, matching GPU hardware texture
// samplers (texel (0,0)'s center sits at UV (0.5/width, 0.5/height)).
function sampleBilinearClamped(source: Raster, u: number, v: number): RGBA {
  const sx = u * source.width - 0.5
  const sy = v * source.height - 0.5
  const x0 = Math.floor(sx)
  const y0 = Math.floor(sy)
  const fx = sx - x0
  const fy = sy - y0

  const p00 = getClamped(source, x0, y0)
  const p10 = getClamped(source, x0 + 1, y0)
  const p01 = getClamped(source, x0, y0 + 1)
  const p11 = getClamped(source, x0 + 1, y0 + 1)

  return {
    r: lerp2D(p00.r, p10.r, p01.r, p11.r, fx, fy),
    g: lerp2D(p00.g, p10.g, p01.g, p11.g, fx, fy),
    b: lerp2D(p00.b, p10.b, p01.b, p11.b, fx, fy),
    a: lerp2D(p00.a, p10.a, p01.a, p11.a, fx, fy),
  }
}

function getClamped(source: Raster, x: number, y: number): RGBA {
  const cx = Math.min(source.width - 1, Math.max(0, x))
  const cy = Math.min(source.height - 1, Math.max(0, y))
  return source.pixels[cy * source.width + cx]
}

function lerp2D(v00: number, v10: number, v01: number, v11: number, fx: number, fy: number): number {
  const top = v00 + (v10 - v00) * fx
  const bottom = v01 + (v11 - v01) * fx
  return top + (bottom - top) * fy
}

// Bounds below are set from a real measured run against
// testdata/drift/golden/ (see the inline worst-observed numbers in each
// comment), not chosen ahead of the measurement -- CLAUDE.md §0 requires a
// bound that's actually measured, not "close enough". mae/max are 0..255
// scale (measureDrift already multiplies by 255); meanDeltaE is CIE76 ΔE.
// Margin is roughly 1.3-1.7x the worst point observed per control, tight
// enough to still catch a real regression, loose enough to absorb
// re-running gendriftgolden after an unrelated govips/libvips patch bump.
interface DriftBounds {
  mae: number
  max: number
  meanDeltaE: number
}

// Light: near bit-exact (Linear1 in Go, same affine math in TS) -- worst
// observed mae=0.379, max=1.16, meanDeltaE=0.292 (light-strong). Extended by
// TASK-highlights-shadows-preview-parity.md (D-25) with two isolated
// highlights/shadows points exercising the new Lab-space tonelut pass:
// light-shadows-strong mae=0.092/max=0.796/meanDeltaE=0.043,
// light-highlights-strong mae=0.218/max=0.892/meanDeltaE=0.123 -- both well
// under light-strong's worst case, so the bound is unchanged.
const LIGHT_BOUNDS: DriftBounds = { mae: 0.6, max: 1.5, meanDeltaE: 0.4 }

// Color: near bit-exact (Lab round-trip matches govips's Modulate/LCH
// path, V-11) -- worst observed mae=0.148, max=0.749, meanDeltaE=0.125
// (color-sat-neg0.5). Extended by TASK-color-cast-preview-parity.md (D-30)
// with two isolated castStrength points: since computeMeanRGB computes the
// exact arithmetic mean (matching govips's Average() exactly) and both
// sides run the same linear-scale formula, these are effectively bit-exact
// -- worst observed mae=0.000016, max=0.0001, meanDeltaE=0.000007
// (color-cast-0.5/1.0, identical to 5 decimal places since the grey-world
// scale factor only depends on castStrength through a linear term). This
// only measures color-math.ts's TS reference against Go -- it does not
// exercise the GPU renderers' box-downsample-pyramid mean approximation
// (webgpu-renderer.ts/webgl2-renderer.ts), which has no non-power-of-two
// bias in this CPU-only test harness; see D-30's resolution note in
// docs/90-deferred-register.md. Bound unchanged -- both new points land
// far inside the existing margin.
const COLOR_BOUNDS: DriftBounds = { mae: 0.25, max: 1.0, meanDeltaE: 0.2 }

// B&W: near bit-exact -- worst observed mae=0.467, max=0.905,
// meanDeltaE=0.221 (bw-skewed).
const BW_BOUNDS: DriftBounds = { mae: 0.7, max: 1.3, meanDeltaE: 0.35 }

// Sharpen: TASK-sharpen-coring-fix.md added libvips' piecewise flat/jaggy
// coring (x1/y2/y3/m1, confirmed via govips' SharpenOptions leaving those
// three unset -- libvips' own C defaults apply) to color-math.ts's
// applyUnsharpMask, closing most of the previous plain-linear-response gap.
// Worst observed post-fix: mae=0.354, max=38.0, meanDeltaE=0.103
// (sharpen-1.0, checkerboard region) -- was mae=0.637, max=87.76,
// meanDeltaE=0.187 before the fix. Bounds set ~1.4-1.6x above the observed
// worst point, matching this file's convention for the other three
// controls.
const SHARPEN_BOUNDS: DriftBounds = { mae: 0.55, max: 50, meanDeltaE: 0.17 }

// V-6 (docs/90-deferred-register.md): confirmed against libvips' own source
// that Go's image.resize (govips Thumbnail -> vips_thumbnail_image) resamples
// with Lanczos3 (libvips/resample/resize.c's vips_resize_class_init default),
// while the live preview resamples with hardware bilinear -- a genuinely
// different algorithm, not a rounding-mode gap. Measured drift confirms it:
// an order of magnitude worse than the near-bit-exact composite controls
// above. Worst observed (resize-inside-upscale, 1.5x upscale -- Lanczos3's
// ringing/overshoot vs. bilinear's plain blur is most visible with no
// downscale-antialiasing question in the way): mae=7.92, max=99.25,
// meanDeltaE=3.70. Other points: resize-inside-half mae=4.41/max=33.0/
// meanDeltaE=2.18, resize-cover-crop mae=2.48/max=34.0/meanDeltaE=1.59.
// Bounds set ~1.3-1.5x above the worst point, matching this file's
// convention -- this is an *accepted* large gap (see new D-23 in
// docs/90-deferred-register.md), not a bug being tracked down.
const RESIZE_BOUNDS: DriftBounds = { mae: 11.0, max: 130, meanDeltaE: 5.0 }

function assertWithinBounds(drift: DriftResult, bounds: DriftBounds): void {
  const mae = Math.max(drift.maeR, drift.maeG, drift.maeB)
  const max = Math.max(drift.maxR, drift.maxG, drift.maxB)
  expect(mae).toBeLessThanOrEqual(bounds.mae)
  expect(max).toBeLessThanOrEqual(bounds.max)
  expect(drift.meanDeltaE).toBeLessThanOrEqual(bounds.meanDeltaE)
}

describe('recipe fidelity drift (V-2)', () => {
  const lightPoints = [
    {
      name: 'light-mild',
      params: { exposure: 0.5, brightness: 0.1, contrast: 0.2, blackPoint: 0.05, highlights: 0, shadows: 0 },
    },
    {
      name: 'light-strong',
      params: { exposure: -0.5, brightness: -0.2, contrast: 0.3, blackPoint: 0.1, highlights: 0, shadows: 0 },
    },
    // Isolated single-param points (docs/tasks/TASK-highlights-shadows-preview-parity.md,
    // resolving D-25) exercising the new Lab-space tonelut pass in
    // applyAdjustLight, kept separate from the RGB-chain points above so
    // drift is attributable to one or the other, not both at once.
    {
      name: 'light-shadows-strong',
      params: { exposure: 0, brightness: 0, contrast: 0, blackPoint: 0, highlights: 0, shadows: 0.7 },
    },
    {
      name: 'light-highlights-strong',
      params: { exposure: 0, brightness: 0, contrast: 0, blackPoint: 0, highlights: 0.7, shadows: 0 },
    },
  ]

  const colorPoints = [
    { name: 'color-sat-0.5', params: { saturation: 0.5, castStrength: 0 } },
    { name: 'color-sat-neg0.5', params: { saturation: -0.5, castStrength: 0 } },
    { name: 'color-sat-1.0', params: { saturation: 1.0, castStrength: 0 } },
    // Isolated single-param points (docs/tasks/TASK-color-cast-preview-parity.md,
    // resolving D-30) exercising the new GPU mean-downsample-pyramid preview
    // pass, kept separate from the saturation points above so drift is
    // attributable to the new mean-reduction math specifically.
    { name: 'color-cast-0.5', params: { saturation: 0.0, castStrength: 0.5 } },
    { name: 'color-cast-1.0', params: { saturation: 0.0, castStrength: 1.0 } },
  ]

  const bwPoints = [
    { name: 'bw-full', params: { intensity: 1.0, neutrals: 0.0, tone: 0.0 } },
    { name: 'bw-skewed', params: { intensity: 0.6, neutrals: 0.5, tone: -0.3 } },
  ]

  const sharpenPoints = [
    { name: 'sharpen-0.3', params: { intensity: 0.3 } },
    { name: 'sharpen-1.0', params: { intensity: 1.0 } },
  ]

  it.each(lightPoints)('Light: $name', ({ name, params }) => {
    const actual = source.pixels.map((p) => applyAdjustLight(p, params))
    const golden = readRaster(join(FIXTURES_DIR, 'golden', `${name}.rgba`)).pixels
    const drift = measureDrift(actual, golden)
    assertWithinBounds(drift, LIGHT_BOUNDS)
  })

  it.each(colorPoints)('Color: $name', ({ name, params }) => {
    const actual = source.pixels.map((p) => applyAdjustColor(p, params, sourceMeanRGB))
    const golden = readRaster(join(FIXTURES_DIR, 'golden', `${name}.rgba`)).pixels
    const drift = measureDrift(actual, golden)
    assertWithinBounds(drift, COLOR_BOUNDS)
  })

  it.each(bwPoints)('B&W: $name', ({ name, params }) => {
    const actual = source.pixels.map((p) => applyBlackAndWhite(p, params))
    const golden = readRaster(join(FIXTURES_DIR, 'golden', `${name}.rgba`)).pixels
    const drift = measureDrift(actual, golden)
    assertWithinBounds(drift, BW_BOUNDS)
  })

  it.each(sharpenPoints)('Sharpen: $name', ({ name, params }) => {
    const blurred = gaussianBlur(source, 0.5, 2)
    const actual = source.pixels.map((p, i) => applyUnsharpMask(p, blurred[i], params.intensity, 'lab-l'))
    const golden = readRaster(join(FIXTURES_DIR, 'golden', `${name}.rgba`)).pixels
    const drift = measureDrift(actual, golden)
    assertWithinBounds(drift, SHARPEN_BOUNDS)
  })
})

describe('image.resize (V-6)', () => {
  const resizePoints = [
    { name: 'resize-inside-half', params: { width: 64, height: 64, fit: 'inside' as const } },
    { name: 'resize-cover-crop', params: { width: 96, height: 48, fit: 'cover' as const } },
    { name: 'resize-inside-upscale', params: { width: 192, height: 192, fit: 'inside' as const } },
  ]

  it.each(resizePoints)('$name', ({ name, params }) => {
    const geometry = computeFitGeometry({ width: source.width, height: source.height }, params)
    const actual = bilinearResample(source, geometry)
    const golden = readRaster(join(FIXTURES_DIR, 'golden', `${name}.rgba`))
    expect(actual.width).toBe(golden.width)
    expect(actual.height).toBe(golden.height)
    const drift = measureDrift(actual.pixels, golden.pixels)
    assertWithinBounds(drift, RESIZE_BOUNDS)
  })
})
