import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import {
  applyAdjustColor,
  applyAdjustLight,
  applyBlackAndWhite,
  applyUnsharpMask,
  gaussianKernel1D,
  rgbToLab,
  type RGBA,
} from './color-math'

// Measures V-2 (docs/90-deferred-register.md): drift between color-math.ts's
// pure-TS reference math -- the source both webgpu-renderer.ts and
// webgl2-renderer.ts are hand-transcribed from -- and the real govips
// output the four composite processors produce
// (workers/internal/processors/{adjust_light,adjust_color,black_and_white,sharpen}.go).
// Fixtures are generated by workers/cmd/gendriftfixture and
// workers/cmd/gendriftgolden (docs/tasks/TASK-recipe-fidelity-drift.md) and
// committed to testdata/drift/ -- raw RGBA8 dumps, not PNGs, so this test
// compares the exact pixels govips decoded/produced without a second image
// decoder in the loop.

const FIXTURES_DIR = join(dirname(fileURLToPath(import.meta.url)), '../../../../../testdata/drift')

interface Raster {
  width: number
  height: number
  pixels: RGBA[] // row-major, normalized 0..1
}

function readRaster(path: string): Raster {
  const buf = readFileSync(path)
  const width = buf.readUInt32LE(0)
  const height = buf.readUInt32LE(4)
  const pixels: RGBA[] = new Array(width * height)
  for (let i = 0; i < width * height; i++) {
    const off = 8 + i * 4
    pixels[i] = {
      r: buf[off] / 255,
      g: buf[off + 1] / 255,
      b: buf[off + 2] / 255,
      a: buf[off + 3] / 255,
    }
  }
  return { width, height, pixels }
}

const source = readRaster(join(FIXTURES_DIR, 'source.rgba'))

interface DriftResult {
  maeR: number
  maeG: number
  maeB: number
  maxR: number
  maxG: number
  maxB: number
  meanDeltaE: number
}

function measureDrift(actual: RGBA[], golden: RGBA[]): DriftResult {
  let sumR = 0
  let sumG = 0
  let sumB = 0
  let maxR = 0
  let maxG = 0
  let maxB = 0
  let sumDeltaE = 0
  const n = actual.length

  for (let i = 0; i < n; i++) {
    const a = actual[i]
    const g = golden[i]
    const dr = Math.abs(a.r - g.r) * 255
    const dg = Math.abs(a.g - g.g) * 255
    const db = Math.abs(a.b - g.b) * 255
    sumR += dr
    sumG += dg
    sumB += db
    if (dr > maxR) maxR = dr
    if (dg > maxG) maxG = dg
    if (db > maxB) maxB = db

    const labA = rgbToLab(a.r, a.g, a.b)
    const labG = rgbToLab(g.r, g.g, g.b)
    sumDeltaE += Math.hypot(labA.l - labG.l, labA.a - labG.a, labA.b - labG.b)
  }

  return {
    maeR: sumR / n,
    maeG: sumG / n,
    maeB: sumB / n,
    maxR,
    maxG,
    maxB,
    meanDeltaE: sumDeltaE / n,
  }
}

// Separable Gaussian blur, sigma/radius matching workers/internal/processors/sharpen.go's
// fixed img.Sharpen(0.5, 2, ...) call -- mirrors what webgpu-renderer.ts /
// webgl2-renderer.ts run as their blur pass before applyUnsharpMask.
// color-math.ts deliberately only exports the per-pixel unsharp half (the
// blur is a spatial pass belonging to the renderers), so this convolution
// is test-local, not reusable renderer code.
function gaussianBlur(raster: Raster, sigma: number, radius: number): RGBA[] {
  const kernel = gaussianKernel1D(sigma, radius)
  const { width, height, pixels } = raster

  const horizontal: RGBA[] = new Array(width * height)
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      let r = 0
      let g = 0
      let b = 0
      for (let k = -radius; k <= radius; k++) {
        const sx = Math.min(width - 1, Math.max(0, x + k))
        const p = pixels[y * width + sx]
        const w = kernel[k + radius]
        r += p.r * w
        g += p.g * w
        b += p.b * w
      }
      horizontal[y * width + x] = { r, g, b, a: pixels[y * width + x].a }
    }
  }

  const vertical: RGBA[] = new Array(width * height)
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      let r = 0
      let g = 0
      let b = 0
      for (let k = -radius; k <= radius; k++) {
        const sy = Math.min(height - 1, Math.max(0, y + k))
        const p = horizontal[sy * width + x]
        const w = kernel[k + radius]
        r += p.r * w
        g += p.g * w
        b += p.b * w
      }
      vertical[y * width + x] = { r, g, b, a: pixels[y * width + x].a }
    }
  }

  return vertical
}

// Bounds below are set from a real measured run against
// testdata/drift/golden/ (see the inline worst-observed numbers in each
// comment), not chosen ahead of the measurement -- CLAUDE.md §0 requires a
// bound that's actually measured, not "close enough". mae/max are 0..255
// scale (measureDrift already multiplies by 255); meanDeltaE is CIE76 ΔE.
// Margin is roughly 1.3-1.7x the worst point observed per control, tight
// enough to still catch a real regression, loose enough to absorb
// re-running gendriftgolden after an unrelated govips/libvips patch bump.
interface DriftBounds {
  mae: number
  max: number
  meanDeltaE: number
}

// Light: near bit-exact (Linear1 in Go, same affine math in TS) -- worst
// observed mae=0.379, max=1.16, meanDeltaE=0.292 (light-strong).
const LIGHT_BOUNDS: DriftBounds = { mae: 0.6, max: 1.5, meanDeltaE: 0.4 }

// Color: near bit-exact (Lab round-trip matches govips's Modulate/LCH
// path, V-11) -- worst observed mae=0.148, max=0.749, meanDeltaE=0.125
// (color-sat-neg0.5).
const COLOR_BOUNDS: DriftBounds = { mae: 0.25, max: 1.0, meanDeltaE: 0.2 }

// B&W: near bit-exact -- worst observed mae=0.467, max=0.905,
// meanDeltaE=0.221 (bw-skewed).
const BW_BOUNDS: DriftBounds = { mae: 0.7, max: 1.3, meanDeltaE: 0.35 }

// Sharpen: TASK-sharpen-coring-fix.md added libvips' piecewise flat/jaggy
// coring (x1/y2/y3/m1, confirmed via govips' SharpenOptions leaving those
// three unset -- libvips' own C defaults apply) to color-math.ts's
// applyUnsharpMask, closing most of the previous plain-linear-response gap.
// Worst observed post-fix: mae=0.354, max=38.0, meanDeltaE=0.103
// (sharpen-1.0, checkerboard region) -- was mae=0.637, max=87.76,
// meanDeltaE=0.187 before the fix. Bounds set ~1.4-1.6x above the observed
// worst point, matching this file's convention for the other three
// controls.
const SHARPEN_BOUNDS: DriftBounds = { mae: 0.55, max: 50, meanDeltaE: 0.17 }

function assertWithinBounds(drift: DriftResult, bounds: DriftBounds): void {
  const mae = Math.max(drift.maeR, drift.maeG, drift.maeB)
  const max = Math.max(drift.maxR, drift.maxG, drift.maxB)
  expect(mae).toBeLessThanOrEqual(bounds.mae)
  expect(max).toBeLessThanOrEqual(bounds.max)
  expect(drift.meanDeltaE).toBeLessThanOrEqual(bounds.meanDeltaE)
}

describe('recipe fidelity drift (V-2)', () => {
  const lightPoints = [
    { name: 'light-mild', params: { exposure: 0.5, brightness: 0.1, contrast: 0.2, blackPoint: 0.05 } },
    { name: 'light-strong', params: { exposure: -0.5, brightness: -0.2, contrast: 0.3, blackPoint: 0.1 } },
  ]

  const colorPoints = [
    { name: 'color-sat-0.5', params: { saturation: 0.5 } },
    { name: 'color-sat-neg0.5', params: { saturation: -0.5 } },
    { name: 'color-sat-1.0', params: { saturation: 1.0 } },
  ]

  const bwPoints = [
    { name: 'bw-full', params: { intensity: 1.0, neutrals: 0.0, tone: 0.0 } },
    { name: 'bw-skewed', params: { intensity: 0.6, neutrals: 0.5, tone: -0.3 } },
  ]

  const sharpenPoints = [
    { name: 'sharpen-0.3', params: { intensity: 0.3 } },
    { name: 'sharpen-1.0', params: { intensity: 1.0 } },
  ]

  it.each(lightPoints)('Light: $name', ({ name, params }) => {
    const actual = source.pixels.map((p) => applyAdjustLight(p, params))
    const golden = readRaster(join(FIXTURES_DIR, 'golden', `${name}.rgba`)).pixels
    const drift = measureDrift(actual, golden)
    assertWithinBounds(drift, LIGHT_BOUNDS)
  })

  it.each(colorPoints)('Color: $name', ({ name, params }) => {
    const actual = source.pixels.map((p) => applyAdjustColor(p, params))
    const golden = readRaster(join(FIXTURES_DIR, 'golden', `${name}.rgba`)).pixels
    const drift = measureDrift(actual, golden)
    assertWithinBounds(drift, COLOR_BOUNDS)
  })

  it.each(bwPoints)('B&W: $name', ({ name, params }) => {
    const actual = source.pixels.map((p) => applyBlackAndWhite(p, params))
    const golden = readRaster(join(FIXTURES_DIR, 'golden', `${name}.rgba`)).pixels
    const drift = measureDrift(actual, golden)
    assertWithinBounds(drift, BW_BOUNDS)
  })

  it.each(sharpenPoints)('Sharpen: $name', ({ name, params }) => {
    const blurred = gaussianBlur(source, 0.5, 2)
    const actual = source.pixels.map((p, i) => applyUnsharpMask(p, blurred[i], params.intensity, 'lab-l'))
    const golden = readRaster(join(FIXTURES_DIR, 'golden', `${name}.rgba`)).pixels
    const drift = measureDrift(actual, golden)
    assertWithinBounds(drift, SHARPEN_BOUNDS)
  })
})
